name: Django CI

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-20.04 (만약 기존 프로젝트와 우분투 충돌시, 2023 최신 22.04)
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4-alpine3.18
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Flake 8 and Black formatter
      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     flake8
      - name: Wait for Database
        run: |
          python wait_for_db.py
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: postgres
          DB_PORT: ${{ secrets.DB_PORT }}

